# Generated by Django 3.0.3 on 2020-02-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clicks',
            new_name='Click',
        ),
    ]
