# Generated by Django 3.0.3 on 2020-02-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200209_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='predecessor',
            new_name='dependency',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='uid',
        ),
        migrations.AddField(
            model_name='course',
            name='parent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
