# Generated by Django 3.0.3 on 2020-02-10 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200209_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='dependency',
        ),
        migrations.AddField(
            model_name='course',
            name='_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Predecessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predecessor_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_course', to='api.Course')),
            ],
        ),
    ]
