# Generated by Django 3.0.3 on 2020-02-10 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200210_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Visit',
            new_name='SiteVisit',
        ),
        migrations.DeleteModel(
            name='Click',
        ),
        migrations.AddField(
            model_name='course',
            name='predecessor',
            field=models.ManyToManyField(related_name='precedes', to='api.Course'),
        ),
        migrations.DeleteModel(
            name='Predecessor',
        ),
        migrations.AddField(
            model_name='linkclick',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course'),
        ),
    ]
