# Generated by Django 3.0.3 on 2020-02-10 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200210_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='_id',
            new_name='ms_id',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='uid',
            new_name='ms_uid',
        ),
        migrations.RemoveField(
            model_name='course',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='linkclick',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='children',
            field=models.ManyToManyField(related_name='parent', to='api.Course'),
        ),
        migrations.AddField(
            model_name='linkclick',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='click_dates', to='api.Course'),
            preserve_default=False,
        ),
    ]
